-- Run this in your MySQL server to create the database and tables

CREATE DATABASE IF NOT EXISTS jlpt_quiz
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE jlpt_quiz;

CREATE TABLE IF NOT EXISTS words (
  id INT AUTO_INCREMENT PRIMARY KEY,
  main_word VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sub_words (
  id INT AUTO_INCREMENT PRIMARY KEY,
  word_id INT NOT NULL,
  kanji VARCHAR(255) NOT NULL,
  hiragana VARCHAR(255) NOT NULL,
  english VARCHAR(255) NOT NULL,
  FOREIGN KEY (word_id) REFERENCES words(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vocab2 (
  id INT AUTO_INCREMENT PRIMARY KEY,
  jp VARCHAR(255) NOT NULL,
  en VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
